// FLT_RADIX
// DECIMAL_DIG
// FLT_DECIMAL_DIG
// DBL_DECIMAL_DIG
// LDBL_DECIMAL_DIB
// FLT_MIN
// DBL_MIN
// LDBL_MIN
// FLT_TRUE_MIN
// DBL_TRUE_MIN
// LDBL_TRUE_MIN
// FLT_MAX
// DBL_MAX
// LDBL_MAX
// FLT_EPSILON
// DBL_EPSILON
// LDBL_EPSILON
// FLT_DIG
// DBL_DIG
// LDBL_DIG
// FLT_MANT_DIG
// DBL_MANT_DIG
// LDBL_MANT_DIG
// FLT_MIN_EXP
// DBL_MIN_EXP
// LDBL_MIN_EXP
// FLT_MIN_10_EXP
// DBL_MIN_10_EXP
// LDBL_MIN_10_EXP
// FLT_MAX_EXP
// DBL_MAX_EXP
// LDBL_MAX_EXP
// FLT_MAX_10_EXP
// DBL_MAX_10_EXP
// LDBL_MAX_10_EXP
// FLT_ROUNTS
// FLT_EVAL_METHOD
// FLT_HAS_SUBNORM
// DBL_HAS_SUBNORM
// LDBL_HAS_SUBNORM

#include <cfloat>

int main()
{
    DBL_MIN_10_EXP
}